Rails:
  Enabled: true

Documentation:
  Enabled: false

AllCops:
  Include:
    - rubocop-rspec
  Exclude:
    - 'Gemfile*'
    - 'Rakefile'
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'spec/rails_helper\.rb'
    - 'spec/spec_helper\.rb'
